### ISSUE TITLE
Label Sync Action Fails with Http Error

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/.github#20] opened 2021-08-17 07:25 UTC
Label Sync Action is failing on certain repositories with error: 

```
Error applying status: help wanted: HttpError: Resource not accessible by integration
```

and

```
HttpError: Resource not accessible by integration
```

![image](https://user-images.githubusercontent.com/4019090/129682261-e69c2215-b9c6-4a05-bf63-8b057405bb14.png)

**Comment by kimburgess** [comment] 2021-09-05 22:35
Resolved via https://github.com/PlaceOS/.github/commit/af1c6e8a90011b6caf0850e1dbd8e2b69f0d97f6.

**Closed by kimburgess** 2021-09-05 22:35 UTC
Labels: type: bug

**Comment by kimburgess** [comment] 2021-09-05 22:45
@jeremyw24 latest sync run: https://github.com/PlaceOS/.github/actions/runs/1204013803

The sync does not delete labels (by design). If you'd like to clean up any deprecated ones, this can be done here: https://github.com/PlaceOS/.github/actions/workflows/delete-org-label.yml
